### ISSUE TITLE
UserStory-5 Delete Party

### ISSUE THREAD

**Issue by CananOzyol** [neuefische/cgn-java-23-2-teamproject-partyplanner#14]
---
name: Delete Party
about: delete existing Party from the Detail Page

---

# User story
As a party planner, I want to be able to delete a party from the detail page, so I can keep my partylist up to date.

# Tasks
### Backend
- [x] Change name of DTO variable in REST controller 
### Frontend
- [x] Add DTO 
- [x] Change Form prop types to DTO 

# Acceptance criteria

- [x] A delete button should be visible on the detail page
- [x] After clicking on the delete button the party is removed from the list
- [x] The User is redirected to the updated party list

# Sprint Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Team understands acceptance criteria 
- [x] Team has defined solution / steps to satisfy acceptance criteria 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified 

# Complexity
5
