### ISSUE TITLE
UserStory-7 Quiz WebClient

### ISSUE THREAD

**Issue by CananOzyol** [neuefische/cgn-java-23-2-teamproject-partyplanner#18]
---
name: Quiz Webclient
about: A random quiz is displayed on the main page

---

# User story
As a User, I want to be able to see a random quiz, so I can solve it and having fun while looking at the partylist.

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [ ] A quiz should be dispayed on the main page 

# Task
- [ ] Implement webclient to fetch a random quiz from external API 

# Sprint Ready Checklist 
- [ ] Acceptance criteria defined 
- [ ] Team understands acceptance criteria 
- [ ] Team has defined solution / steps to satisfy acceptance criteria 
- [ ] Acceptance criteria is verifiable / testable 
- [ ] External / 3rd Party dependencies identified 

# Complexity
13
