### ISSUE TITLE
UserStory-1 Partylist

### ISSUE THREAD

**Issue by Pia0912** [neuefische/cgn-java-23-2-teamproject-partyplanner#2]
---
name: Partylist
about: Show a list of all parties in the animal shelter.
---

# User story
As a party planner, I want to see a list of parties, so I can get an overview of all parties hosted at our animal shelter.

# Acceptance criteria

- [x] Each Party should display a `heading`
- [x] Each Party should display a `date`
- [x] Each Party should display a `location`
- [x] Each Party should display a `number of guests`

# Tasks
- [x] Example task

# Sprint Ready Checklist 
- [x] Acceptance criteria defined 
- [x] Team understands acceptance criteria 
- [x] Team has defined solution / steps to satisfy acceptance criteria 
- [x] Acceptance criteria is verifiable / testable 
- [x] External / 3rd Party dependencies identified 

![Image](https://github.com/neuefische/cgn-java-23-2-teamproject-partyplanner/assets/134581160/50f45f9b-a76b-4787-ae56-49a3700a4ab2)

# Complexity
8
